export const ActionTypes = {
  // products
  FETCH_ALL_PRODUCTS: "FETCH_ALL_PRODUCTS",
  ORDER_PRODUCTS_BY_PRICE: "ORDER_PRODUCTS_BY_PRICE",
  // cart
  ADD_TO_CART: "ADD_TO_CART",
  REMOVE_FROM_CART: "REMOVE_FROM_CART",
};
