export const ActionTypes = {
  // products
  FETCH_ALL_PRODUCTS: "FETCH_ALL_PRODUCTS",
  ORDER_PRODUCTS_BY_PRICE: "ORDER_PRODUCTS_BY_PRICE",
  FILTER_PRODUCTS_BY_SIZE: "FILTER_PRODUCTS_BY_SIZE",
  // cart
  ADD_TO_CART: "ADD_TO_CART",
  REMOVE_FROM_CART: "REMOVE_FROM_CART",
  CLEAR_CART: "CLEAR_CART",
  // orders
  CLEAR_ORDER: "CLEAR_ORDER",
  SHOW_ORDER_FORM: "SHOW_ORDER_FORM",
  HIDE_ORDER_FORM: "HIDE_ORDER_FORM",
  CREATE_ORDER: "CREATE_ORDER",
};
